### ISSUE TITLE
Some code format error exists in `meterlogger.py`

### ISSUE THREAD

**Issue by TuXiaokang** [pytorch/tnt#56]
error message like this

```
>>> import torchnet
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/torchnet/__init__.py", line 5, in <module>
    from . import logger
  File "/usr/local/lib/python3.6/site-packages/torchnet/logger/__init__.py", line 2, in <module>
    from .meterlogger import MeterLogger
  File "/usr/local/lib/python3.6/site-packages/torchnet/logger/meterlogger.py", line 16
    self.nclass = nclass
                       ^
TabError: inconsistent use of tabs and spaces in indentation
```

**Comment by imaxpayne** [comment]
I am facing the same problem

**Comment by praisethemoon** [comment]
Same issue here is as well, fresh `pip3` install on ubuntu `16.04`

**Comment by barrykui** [comment]
All of you are using python3? Let me check that.

**Comment by szagoruyko** [comment]
this fixes it https://github.com/pytorch/tnt/pull/57, waiting for travis to finish and merge
to avoid this in future we need to add to travis py3 builds and flake8
