### ISSUE TITLE
Can't update loss with MeterLogger.

### ISSUE THREAD

**Issue by TuXiaokang** [pytorch/tnt#58]
this was caused by error indent in #[85](https://github.com/pytorch/tnt/blob/7b1dc6ca4a5dda3207e24eb7bd4d3c2a5fdb0a32/torchnet/logger/meterlogger.py#L85)

**Comment by TuXiaokang** [comment]
same problem with updateMeter #[78]https://github.com/pytorch/tnt/blob/7b1dc6ca4a5dda3207e24eb7bd4d3c2a5fdb0a32/torchnet/logger/meterlogger.py#L78

**Comment by szagoruyko** [comment]
oops, sorry! will fix now

**Comment by barrykui** [comment]
What's the type of the loss you used in `mlog.updateLoss()` ?  Variable or Tensor?
There is another example may contribute to you.
https://github.com/barrykui/pytorch_online_ploter

**Comment by TuXiaokang** [comment]
@szagoruyko #[printMeter](https://github.com/pytorch/tnt/blob/7b1dc6ca4a5dda3207e24eb7bd4d3c2a5fdb0a32/torchnet/logger/meterlogger.py#L104) was still has not be fixed.

btw, there comes another problem when i run [pytorch_online_ploter](https://github.com/barrykui/pytorch_online_ploter):
```
Exception in user code:
------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/connection.py", line 83, in create_connection
    raise err
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 166, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x11721fb38>: Failed to establish a new connection: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=9999): Max retries exceeded with url: /events (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11721fb38>: Failed to establish a new connection: [Errno 61] Connection refused',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/visdom/__init__.py", line 261, in _send
    data=json.dumps(msg),
  File "/usr/local/lib/python3.6/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=9999): Max retries exceeded with url: /events (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11721fb38>: Failed to establish a new connection: [Errno 61] Connection refused',))

```
 I have no idea how to address it.

**Comment by barrykui** [comment]
@TuXiaokang Check your Visdom port. It seem that your port is the right one.
You could run by 
```bash
python -m visdom.server # default port is 8097
CUDA_VISIBLE_DEVICES=1 python mnist.py --port 8097
```
Or
```bash
python -m visdom.server -port 9999
CUDA_VISIBLE_DEVICES=1 python mnist.py --port 9999
```

**Comment by TuXiaokang** [comment]
@barrykui it works, thank you!

i hope it can plot charts on different `env` not only `main`.

**Comment by barrykui** [comment]
Me too. haha. 
MeterLogger only provide plot line and confusion matrix. If you have some idea about plotting charts, tell me or contribute to [tnt](https://github.com/pytorch/tnt).

For different **env**,  you could set keywords in the title option in `mlog = MeterLogger(server="Server's IP", nclass=10, title="keywords")`, and then filter the keywords in visdom.
