### ISSUE TITLE
How I can fix this connection error?

### ISSUE THREAD

**Issue by deepaksharma36** [pytorch/tnt#77]
Exception in user code:
------------------------------------------------------------
Traceback (most recent call last):
  File "/home/deepak/softwares/miniconda3/lib/python3.6/site-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/home/deepak/softwares/miniconda3/lib/python3.6/site-packages/urllib3/util/connection.py", line 83, in create_connection
    raise err
  File "/home/deepak/softwares/miniconda3/lib/python3.6/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

**Comment by deepaksharma36** [comment]
Port was in use by some other application
